export const EDIBLES = [
  ["Wyld", "Raspberry Sativa Gummies", "Gummies", "Sativa", "20 pk", 10.0, 0.0, 22, null, "orange", ["Bestseller"]],
  ["Kiva Confections", "Dark Chocolate Bar", "Chocolate", "Hybrid", "100mg", 5.0, 0.0, 20, 26, "ink", ["Deal"]],
  ["Camino", "Midnight Blueberry", "Gummies", "Indica", "20 pk", 5.0, 1.0, 18, null, "purple", ["Sleep"]],
  ["Papa & Barkley", "Releaf Gummies", "Gummies", "Hybrid", "10 pk", 10.0, 10.0, 28, null, "green", ["1:1 CBD"]],
  ["Punch Edibles", "Peanut Butter Bar", "Chocolate", "Indica", "225mg", 25.0, 0.0, 16, 22, "linen", ["Deal", "High dose"]],
  ["Kanha", "Watermelon Nano", "Gummies", "Hybrid", "20 pk", 10.0, 0.0, 24, null, "orange", ["Fast onset"]],
  ["Plus Products", "Uplift Mints", "Mints", "Sativa", "40 pk", 5.0, 0.0, 21, null, "ink", []],
  ["Petra", "Moroccan Mint", "Mints", "Hybrid", "42 pk", 2.5, 0.0, 20, null, "purple", ["Microdose"]],
  ["Terra", "Blueberries", "Chocolate", "Hybrid", "20 pk", 5.0, 0.0, 22, null, "green", []],
  ["Lost Farm", "Strawberry Live Rosin Chews", "Caramels & chews", "Hybrid", "10 pk", 10.0, 0.0, 26, null, "linen", ["Solventless"]],
  ["Wana", "Sour Watermelon", "Gummies", "Hybrid", "10 pk", 10.0, 0.0, 20, null, "orange", []],
  ["Incredibles", "Boulder Bar", "Chocolate", "Indica", "100mg", 10.0, 0.0, 18, null, "ink", []],
  ["District Edibles", "Mango Indica Gummies", "Gummies", "Indica", "10 pk", 10.0, 0.0, 15, 20, "purple", ["Deal"]],
  ["Smokiez", "Sour Blue Raspberry", "Gummies", "Hybrid", "10 pk", 10.0, 0.0, 17, null, "green", []],
  ["Garden Society", "Rose Petal Chocolate", "Chocolate", "Hybrid", "10 pk", 5.0, 0.0, 24, null, "linen", ["Microdose"]],
  ["Kiva Confections", "Camino Wild Berry", "Gummies", "Sativa", "20 pk", 5.0, 0.0, 18, null, "orange", []],
  ["Flav", "Sour Belts", "Hard candy", "Hybrid", "10 pk", 10.0, 0.0, 16, null, "ink", []],
  ["Wyld", "Elderberry Indica", "Gummies", "Indica", "20 pk", 10.0, 0.0, 22, null, "purple", ["Sleep", "Bestseller"]],
  ["Kanha", "Tranquility Belts", "Caramels & chews", "Indica", "10 pk", 10.0, 5.0, 25, null, "green", ["Sleep"]],
  ["Punch Edibles", "Cookies & Cream", "Baked goods", "Hybrid", "225mg", 25.0, 0.0, 16, null, "linen", ["High dose"]],
  ["Plus Products", "Rainbow Sherbet Tablets", "Tablets & capsules", "Hybrid", "20 pk", 5.0, 0.0, 19, null, "orange", []],
  ["Kiva Confections", "Churro Milk Chocolate", "Chocolate", "Hybrid", "100mg", 5.0, 0.0, 21, null, "ink", ["New drop"]],
];

export const BEVERAGES = [
  ["Cann", "Grapefruit Rosé Social Tonic", "Tonics", "Hybrid", "6 pk", 2.0, 4.0, 26, null, "green", ["Microdose"]],
  ["Keef", "Bubba Kush Root Beer", "Sodas", "Indica", "12 oz", 10.0, 0.0, 8, null, "orange", []],
  ["Pabst Labs", "Lemon Seltzer", "Seltzers", "Hybrid", "12 oz", 5.0, 0.0, 7, null, "ink", []],
  ["Uncle Arnie's", "Iced Tea Lemonade", "Teas", "Indica", "8 oz", 100.0, 0.0, 12, null, "purple", ["High dose"]],
  ["BREZ", "Lift Blend", "Seltzers", "Hybrid", "4 pk", 2.5, 5.0, 24, null, "linen", ["Microdose"]],
  ["Kikoko", "Positivi-Tea", "Teas", "Sativa", "10 pk", 5.0, 0.0, 28, null, "green", []],
  ["Cann", "Blood Orange Cardamom", "Tonics", "Hybrid", "6 pk", 2.0, 4.0, 26, 32, "orange", ["Deal", "Microdose"]],
  ["Keef", "Orange Kush Soda", "Sodas", "Hybrid", "12 oz", 10.0, 0.0, 8, null, "ink", []],
  ["Pabst Labs", "Strawberry Kiwi Seltzer", "Seltzers", "Sativa", "4 pk", 5.0, 0.0, 24, null, "purple", []],
  ["Uncle Arnie's", "Watermelon Punch", "Shots", "Hybrid", "8 oz", 100.0, 0.0, 12, null, "linen", ["High dose"]],
  ["Kikoko", "Sympa-Tea", "Teas", "Indica", "10 pk", 3.0, 5.0, 28, null, "green", ["1:1 CBD"]],
  ["BREZ", "Mushroom + THC Blend", "Drink powders", "Hybrid", "12 pk", 2.5, 2.5, 45, null, "orange", ["Microdose"]],
];
