export const VAPE = [
  ["STIIIZY", "Blue Burst Pod", "Pods", "Hybrid", "1g", 87.3, 0.0, 40, null, "ink", ["Bestseller"]],
  ["Raw Garden", "Sour Apple Refined Live Resin", "Live resin carts", "Sativa", "1g", 82.9, 0.1, 35, 45, "green", ["Deal"]],
  ["Heavy Hitters", "Northern Lights", "Cartridges", "Indica", "1g", 91.4, 0.0, 48, null, "purple", ["High potency"]],
  ["Friendly Farms", "Zkittlez Live Resin", "Live resin carts", "Indica", "1g", 79.2, 0.3, 55, null, "orange", ["Solventless"]],
  ["Select", "Elite Live Tangie", "Cartridges", "Sativa", "0.5g", 84.6, 0.0, 25, 32, "linen", ["Deal"]],
  ["Jeeter", "Citrus Slushie Disposable", "Disposables", "Hybrid", "1g", 88.1, 0.0, 30, null, "ink", ["Disposable"]],
  ["Bloom", "Strawberry Cough Cart", "Cartridges", "Sativa", "1g", 85.0, 0.2, 33, null, "green", []],
  ["Cookies", "Gary Payton Pod", "Pods", "Hybrid", "1g", 89.7, 0.0, 50, null, "purple", ["New drop"]],
  ["Rove", "Featured Farms Lemon Tree", "Cartridges", "Sativa", "1g", 83.4, 0.1, 38, null, "orange", []],
  ["Timeless", "Blue Dream Cart", "Distillate carts", "Sativa", "1g", 90.2, 0.0, 32, null, "linen", ["Value"]],
  ["Absolute Xtracts", "Sunset Sherbet", "Cartridges", "Hybrid", "1g", 78.6, 0.4, 36, null, "ink", []],
  ["Dime Industries", "Watermelon Z Disposable", "Disposables", "Hybrid", "2g", 86.9, 0.0, 45, null, "green", ["Disposable"]],
  ["Cake", "Banana OG All-in-One", "Disposables", "Indica", "2g", 88.4, 0.0, 42, 50, "purple", ["Deal", "Disposable"]],
  ["Legion of Bloom", "Terroir Jack Herer", "Live resin carts", "Sativa", "0.5g", 76.3, 0.2, 40, null, "orange", []],
  ["STIIIZY", "Biscotti Pod", "Pods", "Indica", "0.5g", 85.7, 0.0, 28, null, "linen", []],
  ["Turn", "Mimosa Pod", "Pods", "Sativa", "1g", 87.8, 0.0, 44, null, "ink", []],
  ["Raw Garden", "Cherry Pie Live Resin", "Live resin carts", "Indica", "0.5g", 81.5, 0.1, 24, null, "green", []],
  ["Heavy Hitters", "Ultra Pure Pineapple Express", "Distillate carts", "Sativa", "2g", 93.1, 0.0, 65, null, "purple", ["High potency"]],
  ["STIIIZY", "Big Battery", "Batteries", "Accessory", "1 unit", 0.0, 0.0, 30, null, "orange", ["Hardware"]],
  ["Bloom", "Surf All-in-One Battery", "Batteries", "Accessory", "1 unit", 0.0, 0.0, 25, null, "linen", ["Hardware"]],
  ["Select", "Squeeze Live Blackberry", "Live resin carts", "Indica", "1g", 80.8, 0.2, 42, null, "ink", []],
  ["Rove", "Icy Mango Disposable", "Disposables", "Sativa", "1g", 84.2, 0.0, 29, null, "green", ["Disposable"]],
];

export const CONCENTRATES = [
  ["710 Labs", "Pineapple #7 Live Rosin", "Live rosin", "Sativa", "1g", 76.4, 0.2, 90, null, "green", ["Solventless", "Top shelf"]],
  ["Nasha", "Papaya Ice Water Hash", "Ice water hash", "Hybrid", "1g", 62.8, 0.3, 55, null, "orange", ["Solventless"]],
  ["Raw Garden", "Sour Apple Sauce", "Sauce", "Sativa", "1g", 78.2, 0.1, 40, null, "purple", []],
  ["Friendly Farms", "Zkittlez Badder", "Badder & batter", "Indica", "1g", 81.6, 0.2, 45, 55, "ink", ["Deal"]],
  ["Buddies", "Wedding Cake Shatter", "Shatter", "Indica", "1g", 79.4, 0.1, 30, null, "linen", ["Value"]],
  ["Emerald Bay Extracts", "GG4 Diamonds", "Diamonds", "Hybrid", "1g", 92.7, 0.0, 60, null, "green", ["High potency"]],
  ["710 Labs", "Zoap Rosin Jam", "Live rosin", "Hybrid", "1g", 74.9, 0.2, 85, null, "orange", ["Solventless"]],
  ["Buddies", "Blue Dream Sugar", "Sugar", "Sativa", "1g", 77.1, 0.2, 32, null, "purple", []],
  ["Emerald Bay Extracts", "Papaya Crumble", "Crumble", "Hybrid", "1g", 75.8, 0.3, 28, null, "ink", ["Value"]],
  ["Raw Garden", "Tangie HTE", "HTE", "Sativa", "1g", 71.2, 0.4, 48, null, "linen", []],
  ["Nasha", "Full Melt Kief", "Kief", "Indica", "1g", 58.4, 0.5, 35, null, "green", ["Solventless"]],
  ["Papa & Barkley", "Releaf RSO", "RSO & extract oils", "Indica", "1g", 68.9, 2.4, 50, null, "orange", ["Wellness"]],
  ["Friendly Farms", "Lemon Tree Live Rosin", "Live rosin", "Sativa", "1g", 73.6, 0.2, 80, 95, "purple", ["Deal", "Solventless"]],
  ["Emerald Bay Extracts", "Gelato Crystalline", "Crystalline", "Hybrid", "1g", 96.4, 0.0, 55, null, "ink", ["High potency"]],
  ["Buddies", "Northern Lights Rosin", "Rosin", "Indica", "1g", 70.3, 0.3, 45, null, "linen", ["Solventless"]],
  ["Nasha", "Runtz Hash Rosin", "Live rosin", "Hybrid", "2g", 75.2, 0.2, 150, null, "green", ["Solventless", "Top shelf"]],
  ["Raw Garden", "Blackberry Diamonds", "Diamonds", "Indica", "1g", 89.8, 0.1, 52, null, "orange", []],
  ["Buddies", "Trainwreck Badder", "Badder & batter", "Sativa", "1g", 76.6, 0.2, 34, null, "purple", []],
];
