/* [brand, name, subcategory, strainType, weight, thc, cbd, price, was|null, colorway, tags] */

export const FLOWER = [
  ["Connected Cannabis Co.", "Biscotti", "Whole bud", "Hybrid", "3.5g", 28.4, 0.1, 42, null, "ink", ["Top shelf"]],
  ["Alien Labs", "Area 41", "Whole bud", "Hybrid", "3.5g", 31.2, 0.0, 55, null, "purple", ["New drop"]],
  ["Glass House Farms", "Lemon Cherry Gelato", "Whole bud", "Indica", "3.5g", 24.7, 0.2, 28, 35, "orange", ["Deal"]],
  ["710 Labs", "Pineapple #7", "Whole bud", "Sativa", "3.5g", 26.9, 0.1, 65, null, "green", ["Small batch"]],
  ["Lowell Farms", "Wedding Cake", "Whole bud", "Indica", "3.5g", 22.1, 0.3, 32, 40, "linen", ["Deal"]],
  ["Pacific Stone", "Blue Dream", "Whole bud", "Sativa", "7g", 19.8, 0.4, 30, null, "ink", ["Value"]],
  ["Claybourne", "Papaya Punch", "Whole bud", "Hybrid", "3.5g", 25.3, 0.1, 38, null, "orange", []],
  ["Almora Farm", "Gushers", "Whole bud", "Hybrid", "14g", 21.6, 0.2, 60, 75, "purple", ["Deal"]],
  ["Jungle Boys", "Zoap", "Whole bud", "Hybrid", "3.5g", 30.1, 0.0, 60, null, "green", ["Top shelf"]],
  ["Fig Farms", "Animal Face", "Whole bud", "Hybrid", "3.5g", 29.4, 0.1, 58, null, "linen", ["Small batch"]],
  ["Wonderbrett", "Orange Banana", "Whole bud", "Sativa", "3.5g", 27.8, 0.1, 55, null, "ink", []],
  ["Sherbinskis", "Sunset Sherbet", "Whole bud", "Hybrid", "3.5g", 24.2, 0.2, 45, null, "purple", []],
  ["Cookies", "Gary Payton", "Whole bud", "Hybrid", "3.5g", 28.9, 0.0, 50, null, "orange", ["Bestseller"]],
  ["Grizzly Peak", "Blueberry Muffin", "Whole bud", "Indica", "3.5g", 23.5, 0.3, 36, null, "green", []],
  ["Humboldt Farms", "Trainwreck", "Whole bud", "Sativa", "3.5g", 21.9, 0.2, 34, null, "linen", []],
  ["Old Pal", "Ready to Roll Shake", "Shake & ground", "Hybrid", "14g", 18.4, 0.4, 25, null, "ink", ["Value"]],
  ["Pure Beauty", "Bubba Kush Smalls", "Smalls", "Indica", "7g", 20.6, 0.3, 28, 34, "orange", ["Deal"]],
  ["Glass House Farms", "Jack Herer Smalls", "Smalls", "Sativa", "14g", 19.2, 0.2, 45, null, "purple", ["Value"]],
  ["Sunset Connect", "Permanent Marker", "Whole bud", "Hybrid", "3.5g", 32.4, 0.0, 68, null, "green", ["Top shelf", "New drop"]],
  ["Doja", "RS11", "Whole bud", "Hybrid", "3.5g", 29.8, 0.1, 52, null, "linen", []],
  ["Gold Flora", "Ice Cream Cake", "Whole bud", "Indica", "3.5g", 26.1, 0.2, 40, null, "ink", []],
  ["Claybourne", "Cereal Milk Infused", "Infused flower", "Hybrid", "3.5g", 38.7, 0.1, 55, null, "orange", ["High potency"]],
  ["Pacific Stone", "Granddaddy Purple", "Big buds", "Indica", "28g", 20.4, 0.3, 90, 110, "purple", ["Deal", "Ounce"]],
  ["Connected Cannabis Co.", "Jealousy", "Whole bud", "Hybrid", "3.5g", 30.6, 0.0, 58, null, "green", ["Bestseller"]],
];

export const PREROLLS = [
  ["Jeeter", "Citrus Slushie Baby Jeeter 5pk", "Multi-packs", "Hybrid", "5 × 0.5g", 34.2, 0.1, 38, null, "orange", ["Infused", "Bestseller"]],
  ["Lowell Farms", "The Sativa 6pk", "Multi-packs", "Sativa", "6 × 0.35g", 21.4, 0.2, 32, null, "linen", []],
  ["Space Coyote", "Blueberry Muffin Infused", "Infused pre-rolls", "Indica", "1g", 36.8, 0.1, 18, null, "purple", ["Infused"]],
  ["Pure Beauty", "Babies 10pk", "Minis", "Hybrid", "10 × 0.35g", 20.8, 0.2, 40, null, "ink", []],
  ["Claybourne", "Papaya Punch Single", "Singles", "Hybrid", "1g", 24.6, 0.1, 9, null, "green", ["Under $10"]],
  ["Jeeter", "Maui Wowie Jeeter Juice", "Infused pre-rolls", "Sativa", "1g", 39.1, 0.0, 22, 28, "orange", ["Deal", "Infused"]],
  ["Cookies", "Cereal Milk Blunt", "Blunts", "Hybrid", "2g", 27.3, 0.0, 30, null, "purple", []],
  ["710 Labs", "Pineapple #7 Hash Hole", "Hash holes", "Sativa", "1g", 45.2, 0.1, 35, null, "green", ["Solventless", "High potency"]],
  ["Old Pal", "Sativa 14pk", "Multi-packs", "Sativa", "14 × 0.5g", 18.9, 0.3, 35, null, "linen", ["Value"]],
  ["Almora Farm", "Gushers 5pk", "Multi-packs", "Hybrid", "5 × 0.7g", 22.7, 0.2, 25, 32, "ink", ["Deal"]],
  ["Alien Labs", "Area 41 Single", "Singles", "Hybrid", "1g", 30.8, 0.0, 16, null, "orange", ["Top shelf"]],
  ["Glass House Farms", "Blue Dream Pack", "Multi-packs", "Sativa", "5 × 0.5g", 20.1, 0.2, 24, null, "purple", []],
  ["Sherbinskis", "Gelato #41 Single", "Singles", "Hybrid", "1g", 26.4, 0.1, 14, null, "green", []],
  ["Space Coyote", "Sungrown Sativa 5pk", "Minis", "Sativa", "5 × 0.4g", 19.6, 0.3, 28, null, "linen", []],
  ["Jungle Boys", "Zoap Blunt", "Blunts", "Hybrid", "2g", 29.9, 0.0, 34, null, "ink", ["Top shelf"]],
  ["Nasha", "Hash Infused Rosin Hole", "Hash holes", "Indica", "1g", 47.6, 0.1, 40, null, "orange", ["Solventless"]],
];
